/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JDialog;
import javax.swing.JPanel;
import repository.Ponuda;

/**
 *
 * @author Cartman
 */
public class FrmMain extends javax.swing.JFrame {
   // private Ponuda ponuda;

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
       // ponuda=new Ponuda();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBarGlavniMeni = new javax.swing.JMenuBar();
        menuPonuda = new javax.swing.JMenu();
        menuItemPrikazPonude = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuPonuda.setText("Ponuda");

        menuItemPrikazPonude.setText("Prikaz ponude");
        menuItemPrikazPonude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPrikazPonudeActionPerformed(evt);
            }
        });
        menuPonuda.add(menuItemPrikazPonude);

        menuBarGlavniMeni.add(menuPonuda);

        jMenu1.setText("Unesi");

        jMenuItem1.setText("Nov monitor");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        menuBarGlavniMeni.add(jMenu1);

        setJMenuBar(menuBarGlavniMeni);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemPrikazPonudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPrikazPonudeActionPerformed
        // TODO add your handling code here:
        JPanel panel=new FrmTabelarniPrikazPonude();
         // TODO add your handling code here:
       // JPanel panel=new FrmTabelarniPrikazPonude(ponuda);
        JDialog dialog=new JDialog(this, true);
        dialog.setTitle("Prikaz sadrzaja ponude");
        dialog.add(panel);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_menuItemPrikazPonudeActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

       // JDialog dialog1=new JDialog(this, true)  ;
        
       // JDialog dialog1= new frmMonitor(this, true,ponuda);
        JDialog dialog1= new frmMonitor(this, true);
        dialog1.setTitle("Unos novog monitora");
        dialog1.setVisible(true);
       // dialog.add(frmMonitor);
        
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menuBarGlavniMeni;
    private javax.swing.JMenuItem menuItemPrikazPonude;
    private javax.swing.JMenu menuPonuda;
    // End of variables declaration//GEN-END:variables
}
