package view;

import domain.Komponenta;
import domain.Monitor;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JPanel;
import repository.Ponuda;

/**
 *
 * @author Jelena Basaric
 */
public class frmMonitor extends javax.swing.JDialog {
   // private Ponuda ponuda;
    /**
     * Creates new form frmMonitor
     */
    public frmMonitor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
       // this.ponuda=ponuda;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUnesiMonitor = new javax.swing.JPanel();
        lblNaziv = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        lblDijagonala = new javax.swing.JLabel();
        txtDijagonala = new javax.swing.JTextField();
        txtRezolucija = new javax.swing.JTextField();
        lblRezolucija = new javax.swing.JLabel();
        txtProdajnaCena = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDobavljac = new javax.swing.JTextField();
        btnSacuvaj = new javax.swing.JButton();
        btnPrikaz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlUnesiMonitor.setBorder(javax.swing.BorderFactory.createTitledBorder("Unesi podatke za novi monitor"));

        lblNaziv.setText("Naziv:");

        txtNaziv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNazivActionPerformed(evt);
            }
        });

        lblDijagonala.setText("Dijagonala");

        lblRezolucija.setText("Rezolucija");

        txtProdajnaCena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdajnaCenaActionPerformed(evt);
            }
        });

        jLabel4.setText("Prodajna cena");

        jLabel5.setText("Dobavljac:");

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        btnPrikaz.setText("Prikaz");
        btnPrikaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikazActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlUnesiMonitorLayout = new javax.swing.GroupLayout(pnlUnesiMonitor);
        pnlUnesiMonitor.setLayout(pnlUnesiMonitorLayout);
        pnlUnesiMonitorLayout.setHorizontalGroup(
            pnlUnesiMonitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUnesiMonitorLayout.createSequentialGroup()
                .addGroup(pnlUnesiMonitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUnesiMonitorLayout.createSequentialGroup()
                        .addComponent(lblNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNaziv))
                    .addGroup(pnlUnesiMonitorLayout.createSequentialGroup()
                        .addComponent(lblDijagonala, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDijagonala, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                    .addGroup(pnlUnesiMonitorLayout.createSequentialGroup()
                        .addComponent(lblRezolucija, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRezolucija, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                    .addGroup(pnlUnesiMonitorLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtProdajnaCena, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                    .addGroup(pnlUnesiMonitorLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDobavljac, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlUnesiMonitorLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnSacuvaj)
                .addGap(29, 29, 29)
                .addComponent(btnPrikaz)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlUnesiMonitorLayout.setVerticalGroup(
            pnlUnesiMonitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUnesiMonitorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUnesiMonitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUnesiMonitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDijagonala, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDijagonala, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUnesiMonitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRezolucija, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRezolucija, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUnesiMonitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProdajnaCena, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUnesiMonitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDobavljac, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(pnlUnesiMonitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacuvaj)
                    .addComponent(btnPrikaz))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlUnesiMonitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(pnlUnesiMonitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        // TODO add your handling code here:
        String naziv=txtNaziv.getText();
        String dobavljac=txtDobavljac.getText();
        String rezolucija=txtRezolucija.getText();
        double dijagonala=Double.parseDouble(txtDijagonala.getText());
        BigDecimal prodajnaCena=new BigDecimal(txtProdajnaCena.getText());
        
        Komponenta k1=new Monitor(naziv, prodajnaCena, dobavljac,dijagonala, rezolucija);
        //Komponenta k2=new Monitor
       // Ponuda ponuda=new Ponuda();
        List<Komponenta> komponente=Ponuda.getInstance().vratiSadrzajPonude();
        komponente.add(k1);
        //this.dispose();
        
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void txtNazivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNazivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNazivActionPerformed

    private void txtProdajnaCenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdajnaCenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdajnaCenaActionPerformed

    private void btnPrikazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikazActionPerformed
        JPanel panel= new FrmTabelarniPrikazPonude();
        JDialog dialog= new JDialog(this, true);
        dialog.add(panel);
        dialog.pack();
        dialog.setVisible(true);
        
    }//GEN-LAST:event_btnPrikazActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrikaz;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblDijagonala;
    private javax.swing.JLabel lblNaziv;
    private javax.swing.JLabel lblRezolucija;
    private javax.swing.JPanel pnlUnesiMonitor;
    private javax.swing.JTextField txtDijagonala;
    private javax.swing.JTextField txtDobavljac;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtProdajnaCena;
    private javax.swing.JTextField txtRezolucija;
    // End of variables declaration//GEN-END:variables
}
